#!/bin/sh
# File generated by ocamlbuild

cd /home/anup/usr/sem4/col226/prolog-interpreter/Prolog-Interpreter-master

rm -f interpreter.cmi
rm -f interpreter.cmo
rm -f lexer.cmi
rm -f lexer.cmo
rm -f lexer.ml
rm -f parser.cmi
rm -f parser.cmo
rm -f parser.ml
rm -f parser.mli
rm -f prolog.cmi
rm -f prolog.cmo
# Also clean the script itself
rm -f /home/anup/usr/sem4/col226/prolog-interpreter/Prolog-Interpreter-master/_build/sanitize.sh
